[package]
name = "nyaa-notifs"
version = "0.1.11"
edition = "2021"
description = "Utility to monitor entries found on the popular torrent page nyaa.si"
authors = ["Vernoxvernax"]
readme = "README.md"
repository = "https://github.com/Vernoxvernax/Nyaa-Notifications"
license = "MIT"

[dependencies]
isahc = "1.7.2"
lettre = { version = "0.10.1", default-features = false, features = ["smtp-transport", "tokio1-rustls-tls", "hostname", "builder"] }
serde = "1.0.152"
serde_derive = "1.0.152"
serenity = { version = "0.11.5", features = ["collector", "rustls_backend"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite", "offline"] }
tokio = { version = "1.23.0", features = ["full"] }
toml = "0.5.10"
chrono = "0.4.23"
reqwest = "0.11.13"
http = "0.2.8"
serde_json = "1.0.91"
html-escape = "0.2.13"
lazy_static = "1.4.0"
