[package]
name = "nyaa-notifs"
version = "0.1.5"
edition = "2021"

[dependencies]
isahc = "1.7.2"
lettre = { version = "0.10.1", default-features = false, features = ["smtp-transport", "tokio1-rustls-tls", "hostname", "builder"] }
serde = "1.0.144"
serde_derive = "1.0.144"
serenity = { version = "0.11.5", features = ["collector", "rustls_backend"] }
sqlx = { version = "0.6.1", features = ["runtime-tokio-native-tls", "sqlite", "offline"] }
tokio = { version = "1.21.0", features = ["full"] }
toml = "0.5.9"
chrono = "0.4.22"
reqwest = "0.11.11"
http = "0.2.8"
serde_json = "1.0.85"
html-escape = "0.2.11"
