name: Rust

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always


jobs:
  new_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build linux binary
        run: cargo build --release
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          preprelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: RECENT_CHANGES.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/nyaa-notifs
          asset_name: nyaa-notifications
          asset_content_type: application/octet-stream
